/*
* Copyright 2026 Rochus Keller <mailto:me@rochus-keller.ch>
*
* This file is part of the Micron language project.
*
* The following is the license that applies to this copy of the
* file. For a license to use the file under conditions
* other than those described here, please email to me@rochus-keller.ch.
*
* GNU General Public License Usage
* This file may be used under the terms of the GNU General Public
* License (GPL) versions 2.0 or 3.0 as published by the Free Software
* Foundation and appearing in the file LICENSE.GPL included in
* the packaging of this file. Please review the following information
* to ensure GNU General Public Licensing requirements will be met:
* http://www.fsf.org/licensing/licenses/info/GPLv2.html and
* http://www.gnu.org/copyleft/gpl.html.
*/

#include "MicAstLoader.h"
#include "MicAst.h"
#include "MicToken.h"
#include "MilAst.h"
#include <QtDebug>
using namespace Mic;

/*
    AstLoader reconstructs a MIC module (i.e. its public interface) from the MIL module
    This is the reverse operation of Mil::IlAstRenderer.
    Here we regenerate just enough Mic AST so the Micron compiler can use a prebuilt
    module as an import, without its source code being present.

    A prebuilt MIL module can be:
    - the interface MIL embedded in an ELF ".micron.mod" section
    - an full MIL module generated by the AST renderer
*/

QByteArray AstLoader::sym(const QByteArray& s)
{
    return Token::getSymbol(s);
}

AstLoader::AstLoader(AstModel* mdl, ModuleResolver* resolver):
    mdl(mdl),resolver(resolver),d_milModule(0),d_micModule(0)
{
}

bool AstLoader::error(const QString& msg)
{
    if( d_error.isEmpty() )
        d_error = msg;
    return false;
}

static int basicKind(int milKind)
{
    switch( milKind )
    {
    case Mil::Type::Undefined:
        return Mic::Type::Undefined;
    case Mil::Type::Any:
        return Mic::Type::Any;
    case Mil::Type::StringLit:
        return Mic::Type::StrLit;
    case Mil::Type::ByteArrayLit:
        return Mic::Type::ByteArrayLit;
    case Mil::Type::NIL:
        return Mic::Type::Nil;
    case Mil::Type::BOOL:
        return Mic::Type::BOOL;
    case Mil::Type::CHAR:
        return Mic::Type::CHAR;
    case Mil::Type::INT8:
        return Mic::Type::INT8;
    case Mil::Type::INT16:
        return Mic::Type::INT16;
    case Mil::Type::INT32:
        return Mic::Type::INT32;
    case Mil::Type::INT64:
        return Mic::Type::INT64;
    case Mil::Type::UINT8:
        return Mic::Type::UINT8;
    case Mil::Type::UINT16:
        return Mic::Type::UINT16;
    case Mil::Type::UINT32:
        return Mic::Type::UINT32;
    case Mil::Type::UINT64:
        return Mic::Type::UINT64;
    case Mil::Type::FLOAT32:
        return Mic::Type::FLT32;
    case Mil::Type::FLOAT64:
        return Mic::Type::FLT64;
    case Mil::Type::INTPTR:
        return Mic::Type::UINT64; // MIC has no dedicated address type
    case Mil::Type::DBLINTPTR:
        return Mic::Type::UINT64;
    default:
        return -1;
    }
}

Declaration* AstLoader::loadModule(Mil::Declaration* milModule)
{
    // reconstruct the given MIL module as a MIC module declaration.
    // the returned declaration is owned by the caller

    d_error.clear();
    d_map.clear();
    d_byName.clear();
    d_milModule = milModule;
    d_micModule = 0;

    if( milModule == 0 || milModule->kind != Mil::Declaration::Module )
    {
        error("not a MIL module");
        return 0;
    }

    d_micModule = new Declaration();
    d_micModule->kind = Declaration::Module;
    d_micModule->name = sym(milModule->name);
    d_micModule->visi = Node::ReadWrite;

    ModuleData md;
    md.fullName = sym(milModule->name); // must match the MIL module name for re-export
    foreach( const QByteArray& seg, milModule->name.split('$') )
        md.path += sym(seg);
    if( milModule->md )
        md.source = milModule->md->source;
    d_micModule->data = QVariant::fromValue(md);

    Mil::Declaration* sub = milModule->subs;
    while( sub )
    {
        // create a shell for every reconstructable member
        createShell(sub);
        sub = sub->next;
    }

    buildHierarchy();

    // fill in types first so type references resolve, then the rest
    sub = milModule->subs;
    while( sub )
    {
        Mil::Declaration* real = ( sub->kind == Mil::Declaration::Placeholder && sub->forwardTo ) ? sub->forwardTo : sub;
        Declaration* micDecl = d_map.value(real);
        if( micDecl && real->kind == Mil::Declaration::TypeDecl )
            fillType(real, micDecl);
        sub = sub->next;
    }
    sub = milModule->subs;
    while( sub )
    {
        Mil::Declaration* real = ( sub->kind == Mil::Declaration::Placeholder && sub->forwardTo ) ? sub->forwardTo : sub;
        Declaration* micDecl = d_map.value(real);
        if( micDecl )
        {
            switch( real->kind )
            {
            case Mil::Declaration::ConstDecl:
                fillConst(real, micDecl);
                break;
            case Mil::Declaration::VarDecl:
                fillVar(real, micDecl);
                break;
            case Mil::Declaration::Procedure:
                fillProc(real, micDecl);
                break;
            }
        }
        sub = sub->next;
    }

    return d_micModule;
}

void AstLoader::createShell(Mil::Declaration* milDecl)
{
    Mil::Declaration* real = milDecl;
    if( milDecl->kind == Mil::Declaration::Placeholder )
    {
        if( milDecl->forwardTo == 0 )
            return;
        real = milDecl->forwardTo;
    }

    if( real->kind == Mil::Declaration::Procedure && real->entryPoint )
        return; // entry/init procedures are not part of the importable interface

    Declaration::Kind micKind = Declaration::NoMode;
    switch( real->kind )
    {
    case Mil::Declaration::TypeDecl:
        micKind = Declaration::TypeDecl;
        break;
    case Mil::Declaration::ConstDecl:
        micKind = Declaration::ConstDecl;
        break;
    case Mil::Declaration::VarDecl:
        micKind = Declaration::VarDecl;
        break;
    case Mil::Declaration::Procedure:
        micKind = Declaration::Procedure;
        break;
    default:
        return; // Import/Importer/Field/etc. are handled elsewhere or not at module level
    }

    if( real->name.isEmpty() )
        return;
    if( d_map.contains(real) )
        return;

    Declaration* micDecl = new Declaration();
    micDecl->kind = micKind;
    micDecl->name = real->name; // final leaf name is assigned in buildHierarchy
    micDecl->visi = real->public_ ? Node::ReadWrite : Node::Private;

    if( micKind == Declaration::TypeDecl )
    {
        // create the type shell up front so references can be bound before the body is filled in
        Type* t = new Type();
        t->kind = Type::Undefined;
        t->decl = micDecl;
        micDecl->setType(t);
        micDecl->ownstype = true;
    }

    d_map.insert(real, micDecl);
    d_byName.insert(real->name, micDecl);
}

void AstLoader::buildHierarchy()
{
    // rebuild the nesting hierarchy from the '$'-flattened names
    // walk the MIL members in declaration order so that the reconstructed sibling lists keep the original order
    Mil::Declaration* sub = d_milModule->subs;
    while( sub )
    {
        Mil::Declaration* real = ( sub->kind == Mil::Declaration::Placeholder && sub->forwardTo ) ?
                    sub->forwardTo : sub;
        Declaration* micDecl = d_map.value(real);
        if( micDecl )
            attachToParent(real, micDecl);
        sub = sub->next;
    }
}

void AstLoader::attachToParent(Mil::Declaration* milDecl, Declaration* micDecl)
{
    // a type-bound procedure belongs to its receiver type
    if( milDecl->kind == Mil::Declaration::Procedure && milDecl->typebound )
    {
        micDecl->name = sym(milDecl->name);
        Declaration* recv = d_map.value(milDecl->outer);
        micDecl->outer = recv ? recv : d_micModule;
        return;
    }

    const QByteArray full = milDecl->name;

    // find the longest '$'-prefix that names an existing (created) declaration;
    // that declaration is the enclosing scope, and the remainder is the leaf name
    Declaration* parent = 0;
    QByteArray leaf = full;
    int pos = full.lastIndexOf('$');
    while( pos > 0 )
    {
        const QByteArray prefix = full.left(pos);
        Declaration* cand = d_byName.value(prefix);
        if( cand && cand != micDecl )
        {
            parent = cand;
            leaf = full.mid(pos+1);
            break;
        }
        pos = full.lastIndexOf('$', pos-1);
    }

    micDecl->name = sym(leaf);
    if( parent )
        micDecl->outer = parent;
    else
        micDecl->outer = d_micModule;

    appendMember(micDecl->outer, micDecl);
}

void AstLoader::appendMember(Declaration* scope, Declaration* member)
{
    if( scope->link == 0 )
        scope->link = member;
    else
        Declaration::append(scope->link, member);
}

Type* AstLoader::mapNamedType(Mil::Type* mt)
{
    if( mt == 0 )
        return 0;

    // after validation the reference carries a decl back-pointer
    if( mt->kind == Mil::Type::NameRef )
    {
        Mil::Type* deref = mt->deref();
        if( deref && deref != mt )
        {
            if( deref->kind < Mil::Type::MaxBasicType )
            {
                const int k = basicKind(deref->kind);
                if( k >= 0 )
                    return mdl->getType(k);
            }
            if( deref->decl && d_map.contains(deref->decl) )
                return d_map.value(deref->decl)->getType();
        }

        const Mil::Quali q = mt->toQuali();
        if( q.first.isEmpty() )
        {
            Declaration* d = d_byName.value(q.second);
            if( d )
                return d->getType();
        }else if( resolver )
        {
            Declaration* mod = resolver->resolveModule(sym(q.first));
            if( mod )
            {
                Declaration* d = mod->find(sym(q.second), false);
                if( d )
                    return d->getType();
            }
        }
        return mdl->getType(Type::Undefined);
    }

    // a directly referenced named type, not the one currently being filled
    if( mt->decl && d_map.contains(mt->decl) )
        return d_map.value(mt->decl)->getType();

    return 0;
}

Type* AstLoader::mapType(Mil::Type* mt)
{
    if( mt == 0 )
        return mdl->getType(Type::NoType);

    if( mt->kind < Mil::Type::MaxBasicType )
    {
        const int k = basicKind(mt->kind);
        if( k >= 0 )
            return mdl->getType(k);
        return mdl->getType(Type::Undefined);
    }

    Type* named = mapNamedType(mt);
    if( named )
        return named;

    // anonymous structural type inlined at the point of use
    return buildInlineType(mt);
}

Type* AstLoader::buildInlineType(Mil::Type* mt)
{
    if( mt == 0 )
        return mdl->getType(Type::NoType);

    switch( mt->kind )
    {
    case Mil::Type::Pointer:
        {
            Type* t = new Type();
            t->kind = Type::Pointer;
            t->setType(mapType(mt->getType()));
            return t;
        }
    case Mil::Type::Array:
        {
            Type* t = new Type();
            t->kind = Type::Array;
            t->len = mt->len;
            t->setType(mapType(mt->getType()));
            return t;
        }
    case Mil::Type::Proc:
        {
            Type* t = new Type();
            t->kind = Type::Proc;
            t->typebound = mt->typebound;
            int i = 0;
            foreach( Mil::Declaration* p, mt->subs )
                t->subs.append(makeParam(p, i++));
            if( mt->getType() )
                t->setType(mapType(mt->getType()));
            return t;
        }
    default:
        // structured named types should already have been resolved via mapNamedType
        return mdl->getType(Type::Undefined);
    }
}

Declaration* AstLoader::makeField(Mil::Declaration* milField)
{
    Declaration* f = new Declaration();
    f->kind = Declaration::Field;
    f->name = sym(milField->name);
    f->visi = milField->public_ ? Node::ReadWrite : Node::Private;
    f->setType(mapType(milField->getType()));
    if( milField->kind == Mil::Declaration::Field )
        f->id = milField->f.bw; // bit width, if any
    return f;
}

Declaration* AstLoader::makeParam(Mil::Declaration* milParam, int index)
{
    Declaration* p = new Declaration();
    p->kind = Declaration::ParamDecl;
    p->name = sym(milParam->name);
    p->visi = Node::Private;
    p->id = index;
    p->setType(mapType(milParam->getType()));
    return p;
}

void AstLoader::fillType(Mil::Declaration* milDecl, Declaration* micDecl)
{
    Mil::Type* mt = milDecl->getType();
    Type* t = micDecl->getType();
    if( mt == 0 || t == 0 )
        return;

    switch( mt->kind )
    {
    case Mil::Type::Struct:
    case Mil::Type::Union:
        {
            t->kind = Type::Record;
            Mil::DeclList fields = mt->getFieldList(false);
            foreach( Mil::Declaration* f, fields )
            {
                Declaration* mf = makeField(f);
                mf->outer = micDecl;
                t->subs.append(mf);
            }
        }
        break;
    case Mil::Type::Object:
        {
            t->kind = Type::Object;
            if( mt->getType() )
                t->setType(mapType(mt->getType())); // base (super) object
            Mil::DeclList fields = mt->getFieldList(false);
            foreach( Mil::Declaration* f, fields )
            {
                Declaration* mf = makeField(f);
                mf->outer = micDecl;
                t->subs.append(mf);
            }
        }
        break;
    case Mil::Type::Interface:
        t->kind = Type::Interface;
        break;
    case Mil::Type::Proc:
        {
            t->kind = Type::Proc;
            t->typebound = mt->typebound;
            int i = 0;
            foreach( Mil::Declaration* p, mt->subs )
            {
                Declaration* mp = makeParam(p, i++);
                mp->outer = micDecl;
                t->subs.append(mp);
            }
            if( mt->getType() )
                t->setType(mapType(mt->getType()));
        }
        break;
    case Mil::Type::Pointer:
        t->kind = Type::Pointer;
        t->setType(mapType(mt->getType()));
        break;
    case Mil::Type::Array:
        t->kind = Type::Array;
        t->len = mt->len;
        t->setType(mapType(mt->getType()));
        break;
    case Mil::Type::Generic:
        t->kind = Type::Generic;
        break;
    case Mil::Type::NameRef:
        {
            // the name resolves to the referenced type, so drop the shell
            // type and bind the declaration directly to the target
            Type* target = mapType(mt);
            if( target && target != t )
            {
                if( micDecl->ownstype )
                    delete t;
                micDecl->ownstype = false;
                micDecl->setType(target);
            }
        }
        break;
    default:
        if( mt->kind < Mil::Type::MaxBasicType )
        {
            const int k = basicKind(mt->kind);
            if( k >= 0 )
            {
                if( micDecl->ownstype )
                    delete t;
                micDecl->ownstype = false;
                micDecl->setType(mdl->getType(k));
            }
        }
        break;
    }
}

void AstLoader::fillProc(Mil::Declaration* milDecl, Declaration* micDecl)
{
    int index = 0;
    Mil::Declaration* sub = milDecl->subs;
    while( sub )
    {
        if( sub->kind == Mil::Declaration::ParamDecl )
        {
            Declaration* p = makeParam(sub, index++);
            p->outer = micDecl;
            appendMember(micDecl, p);
        }
        sub = sub->next;
    }
    if( milDecl->getType() )
        micDecl->setType(mapType(milDecl->getType()));

    micDecl->extern_ = true; // a reconstructed procedure has no MIC body; instead we declare it extern_
    micDecl->invar = milDecl->invar;
    micDecl->inline_ = milDecl->inline_;

    if( !milDecl->typebound )
        return;

    // a type-bound procedure becomes a member of its receiver type
    Declaration* recvDecl = d_map.value(milDecl->outer);
    if( recvDecl && recvDecl->getType() )
    {
        micDecl->typebound = true;
        micDecl->outer = recvDecl;
        recvDecl->getType()->subs.append(micDecl);
    }
}

void AstLoader::fillConst(Mil::Declaration* milDecl, Declaration* micDecl)
{
    Mil::Constant* c = milDecl->c;

    Type* t = milDecl->getType() ? mapType(milDecl->getType()) : 0;

    if( c )
    {
        switch( c->kind )
        {
        case Mil::Constant::I:
            micDecl->data = QVariant::fromValue((qlonglong)c->i);
            if( t == 0 )
                t = mdl->getType(Type::INT64);
            break;
        case Mil::Constant::D:
            micDecl->data = QVariant::fromValue((double)c->d);
            if( t == 0 )
                t = mdl->getType(Type::FLT64);
            break;
        case Mil::Constant::P:
            micDecl->data = QVariant::fromValue((qulonglong)c->p);
            if( t == 0 )
                t = mdl->getType(Type::UINT64);
            break;
        case Mil::Constant::S:
            micDecl->data = QVariant::fromValue(QByteArray(c->s));
            if( t == 0 )
                t = mdl->getType(Type::StrLit);
            break;
        default:
            // structured (B/C) or reference (R) constants are not reconstructed as values here
            break;
        }
    }

    if( t )
        micDecl->setType(t);
}

void AstLoader::fillVar(Mil::Declaration* milDecl, Declaration* micDecl)
{
    micDecl->setType(mapType(milDecl->getType()));
}
