#ifndef __MIL_PARSER__
#define __MIL_PARSER__
// This file was automatically generated by EbnfStudio; don't modify it!

#include <Micron/MilToken.h>
#include <QList>

namespace Mil {

	class Scanner {
	public:
		virtual Token next() = 0;
		virtual Token peek(int offset) = 0;
	};

	class Parser {
	public:
		Parser(Scanner* s):scanner(s) {}
		void RunParser();
		struct Error {
		    QString msg;
		    int row, col;
		    QString path;
		    Error( const QString& m, int r, int c, const QString& p):msg(m),row(r),col(c),path(p){}
		};
		QList<Error> errors;
	protected:
		void Mil();
		void integer();
		void number();
		void qualident();
		void trident();
		void qortrident();
		void identdef();
		void regwidth();
		void Line();
		void ConstDeclaration();
		void TypeDeclaration();
		void type();
		void NamedType();
		void ArrayType();
		void length();
		void StructUnionType();
		void FieldList();
		void IdentList();
		void InterfaceType();
		void ObjectType();
		void MemberList();
		void PointerType();
		void ProcedureType();
		void VariableDeclaration();
		void ProcedureDeclaration();
		void Binding();
		void ProcedureBody();
		void LocalDeclaration();
		void FormalParameters();
		void ReturnType();
		void FPSection();
		void module();
		void ImporterList();
		void ImportList();
		void import();
		void instantiation();
		void DeclarationSequence();
		void Expression();
		void ExpInstr();
		void CondOp();
		void StatementSequence();
		void Statement();
		void IfThenElse();
		void Loop();
		void Switch();
		void RepeatUntil();
		void WhileDo();
		void MetaActuals();
		void MetaParams();
		void ConstExpression();
		void ConstExpression2();
		void constructor();
		void component_list();
		void component();
	protected:
		Token cur;
		Token la;
		Scanner* scanner;
		void next();
		Token peek(int off);
		void invalid(const char* what);
		bool expect(int tt, bool pkw, const char* where);
	};
}
#endif // include
