#ifndef __MIC$_INCLUDED__
#define __MIC$_INCLUDED__

#include <inttypes.h>

// MIC$.h
// this file was generated by MilCompiler  on Sa. Apr. 26 00:18:50 2025
// manually modified

typedef char MIC$$_$1[];
typedef char* MIC$$_$2;
extern uint32_t MIC$$relop1(const char* lhs, const char* rhs, int op);
extern uint32_t MIC$$relop2(const char* lhs, const char rhs, int op);
extern uint32_t MIC$$relop3(char lhs, const char* rhs, int op);
extern uint32_t MIC$$relop4(char lhs, char rhs, int op);
extern uint32_t MIC$$SetDiv(uint32_t lhs, uint32_t rhs);
extern uint32_t MIC$$SetIn(uint32_t lhs, uint32_t rhs);
extern uint32_t MIC$$SetRange(uint32_t lhs, uint32_t rhs);
extern void MIC$$printI8(int64_t i);
extern void MIC$$printU8(uint64_t u);
extern void MIC$$printF8(double f);
extern void MIC$$printStr(const char* s);
extern void MIC$$printCh(char c);
extern void MIC$$printBool(uint8_t b);
extern void MIC$$printSet(uint32_t s);
extern void MIC$$strcopy(char* lhs, char* rhs);
extern void MIC$$assert(uint8_t cond, uint32_t line, const char* file);
extern void MIC$$begin$();
extern void MIC$$exit(int res);
extern uint32_t MIC$$strlen(char* str);
extern void MIC$$strcpy(char* to, char* from, int n);

extern void* MIC$$alloc(uint32_t size);
extern void MIC$$free(void* ptr);
extern void* MIC$$calloc(uint32_t size);
extern void* MIC$$gcalloc(uint32_t size);

#if 0
extern int32_t MIC$$obdiv32(int32_t x, int32_t y);
extern int32_t MIC$$obmod32(int32_t x, int32_t y);
extern int64_t MIC$$obdiv64(int64_t x, int64_t y);
extern int64_t MIC$$obmod64(int64_t x, int64_t y);
#endif

#endif // __MIC$_INCLUDED__

