#ifndef __FILES_INCLUDED__
#define __FILES_INCLUDED__

// Files.h
// this file was generated by Micron IDE 0.3.9 on Di. Jan. 27 23:40:25 2026

typedef struct Files$Handle {
} Files$Handle;
typedef struct Files$Handle* Files$File;
// no typedef for open array Files$_$2 (char*);
typedef char* Files$_$3;
typedef int* Files$_$4;
typedef unsigned char* Files$_$5;
typedef long long* Files$_$6;
typedef float* Files$_$7;
typedef double* Files$_$8;
typedef unsigned int* Files$_$9;
typedef unsigned char* Files$_$10;
// no typedef for open array Files$_$11 (unsigned char*);
typedef unsigned char* Files$_$12;

extern struct Files$Handle* Files$Old(char* name);
extern struct Files$Handle* Files$New(char* name);
extern void Files$Close(struct Files$Handle* f);
extern void Files$Delete(char* name, int* res);
extern void Files$Rename(char* old, char* new, int* res);
extern int Files$Length(struct Files$Handle* f);
extern unsigned char Files$Eof(struct Files$Handle* f);
extern void Files$CreationDate(struct Files$Handle* f, int* t, int* d);
extern void Files$ModificationDate(struct Files$Handle* f, int* t, int* d);
extern unsigned char Files$Set(struct Files$Handle* f, int pos);
extern int Files$Pos(struct Files$Handle* f);
extern unsigned char Files$Read(struct Files$Handle* f, unsigned char* x);
extern unsigned char Files$ReadInt(struct Files$Handle* f, int* x);
extern unsigned char Files$ReadLInt(struct Files$Handle* f, long long* x);
extern unsigned char Files$ReadReal(struct Files$Handle* f, float* x);
extern unsigned char Files$ReadLReal(struct Files$Handle* f, double* x);
extern unsigned char Files$ReadNum(struct Files$Handle* f, int* x);
extern int Files$ReadString(struct Files$Handle* f, char* x);
extern unsigned char Files$ReadSet(struct Files$Handle* f, unsigned int* x);
extern unsigned char Files$ReadBool(struct Files$Handle* f, unsigned char* x);
extern int Files$ReadBytes(struct Files$Handle* f, unsigned char* x, int n);
extern unsigned char Files$Write(struct Files$Handle* f, unsigned char x);
extern unsigned char Files$WriteInt(struct Files$Handle* f, int x);
extern unsigned char Files$WriteLInt(struct Files$Handle* f, long long x);
extern unsigned char Files$WriteReal(struct Files$Handle* f, float x);
extern unsigned char Files$WriteLReal(struct Files$Handle* f, double x);
extern unsigned char Files$WriteNum(struct Files$Handle* f, int x);
extern int Files$WriteString(struct Files$Handle* f, char* x);
extern unsigned char Files$WriteSet(struct Files$Handle* f, unsigned int x);
extern unsigned char Files$WriteBool(struct Files$Handle* f, unsigned char x);
extern int Files$WriteBytes(struct Files$Handle* f, unsigned char* x, int n);
extern void Files$begin$();

#endif // __FILES_INCLUDED__

