#ifndef __IN_INCLUDED__
#define __IN_INCLUDED__

// In.h
// this file was generated by Micron IDE 0.3.9 on Di. Jan. 27 23:40:25 2026

typedef char* In$_$17;
typedef int* In$_$18;
typedef long long* In$_$19;
typedef float* In$_$20;
typedef double* In$_$21;
// no typedef for open array In$_$22 (char*);
typedef char* In$_$23;

extern unsigned char In$Done;
extern void In$Open();
extern void In$Char(char* ch);
extern void In$Int(int* i);
extern void In$LongInt(long long* i);
extern void In$Real(float* x);
extern void In$LongReal(double* y);
extern void In$String(char* str);
extern void In$Name(char* name);
extern void In$begin$();

#endif // __IN_INCLUDED__

