#ifndef __INPUT_INCLUDED__
#define __INPUT_INCLUDED__

// Input.h
// this file was generated by MilCompiler  on Sa. Apr. 26 00:18:50 2025


typedef char* Input$_$1;
typedef unsigned int* Input$_$2;
typedef int* Input$_$3;
extern int Input$Available();
extern void Input$Read(char* ch);
extern void Input$Mouse(unsigned int* keys, int* x, int* y);
extern void Input$SetMouseLimits(int w, int h);
extern int Input$Time();
extern void Input$begin$();

#endif // __INPUT_INCLUDED__

