#ifndef __INPUT_INCLUDED__
#define __INPUT_INCLUDED__

// Input.h
// this file was generated by Micron IDE 0.3.9 on Di. Jan. 27 23:40:25 2026

typedef char* Input$_$24;
typedef unsigned int* Input$_$25;
typedef int* Input$_$26;

extern int Input$Available();
extern void Input$Read(char* ch);
extern void Input$Mouse(unsigned int* keys, int* x, int* y);
extern void Input$SetMouseLimits(int w, int h);
extern int Input$Time();
extern void Input$begin$();

#endif // __INPUT_INCLUDED__

