#ifndef __OUT_INCLUDED__
#define __OUT_INCLUDED__

// Out.h
// this file was generated by MilCompiler  on Sa. Apr. 26 00:18:50 2025


typedef char Out$_$1[];
typedef char* Out$_$2;
extern void Out$Open();
extern void Out$Char(char ch);
extern void Out$String(char* str);
extern void Out$Int(long long i, int n);
extern void Out$Real(float x, int n);
extern void Out$LongReal(double x, int n);
extern void Out$Ln();
extern void Out$begin$();

#endif // __OUT_INCLUDED__

