#ifndef __STRINGS_INCLUDED__
#define __STRINGS_INCLUDED__

// Strings.h
// this file was generated by Micron IDE 0.3.9 on Di. Jan. 27 23:40:25 2026

// no typedef for open array Strings$_$13 (char*);
typedef char* Strings$_$14;

extern int Strings$Length(char* s);
extern void Strings$Insert(char* source, int pos, char* dest);
extern void Strings$Append(char* extra, char* dest);
extern void Strings$Delete(char* s, int pos, int n);
extern void Strings$Replace(char* source, int pos, char* dest);
extern void Strings$Extract(char* source, int pos, int n, char* dest);
extern int Strings$Pos(char* pattern, char* s, int pos);
extern void Strings$Cap(char* s);
extern void Strings$begin$();

#endif // __STRINGS_INCLUDED__

